name: CI Pipeline - Push to ACR

on:
  push:
    branches:
      - testing

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      # Build & Push Frontend
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} ./frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}

      # Build & Push Product Service
      - name: Build and Push Product Service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product:${{ env.IMAGE_TAG }} ./backend/product
          docker push ${{ env.ACR_LOGIN_SERVER }}/product:${{ env.IMAGE_TAG }}

      # Build & Push Order Service
      - name: Build and Push Order Service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order:${{ env.IMAGE_TAG }} ./backend/order
          docker push ${{ env.ACR_LOGIN_SERVER }}/order:${{ env.IMAGE_TAG }}

      # Build & Push Customer Service
      - name: Build and Push Customer Service
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/customer:${{ env.IMAGE_TAG }} ./backend/customer
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer:${{ env.IMAGE_TAG }}
