name: CI Pipeline - Push to ACR

on:
  push:
    branches:
      - testing

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Build and Push frontend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} ./frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}

      - name: Build and Push product
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product:${{ github.sha }} ./backend/product
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product:${{ github.sha }}

      - name: Build and Push order
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order:${{ github.sha }} ./backend/order
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order:${{ github.sha }}

      - name: Build and Push customer
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer:${{ github.sha }} ./backend/customer
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer:${{ github.sha }}
